# Generated by Django 4.0.4 on 2022-12-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0002_tag_alter_theme_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dream.tag'),
        ),
    ]
