# Generated by Django 4.0.4 on 2022-12-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0003_dream_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
